apiVersion: v1
kind: Service
metadata:
  name: finance-web
  labels:
    app: finance-web
spec:
  ports:
    - name: port3000
      port: 3000
      targetPort: 3000
  selector:
    app: finance-web
  type: ClusterIP
