apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: -1
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: adminpassword

---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: 0
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: quay.io/jkeam/finance-web
        command: ["./bin/rails"]
        args: ["db:prepare"]
        envFrom:
        - secretRef:
            name: db-credentials
      restartPolicy: Never
