apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finance

images:
- name: quay.io/jkeam/finance-web
  digest: sha256:1ce91bd2ea5eaf8a082fbe748d68678f19f0efb84cfba23bab26d752cea5d03d

resources:
  - namespace.yaml
  - app
